# =======================================================
# Lite Docker Compose for SwapStreet ( in-mem backend DB)
# =======================================================

services:
  # ==========================
  # Backend service (.NET API)
  # ==========================
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      USE_INMEMORY_DB: "true"
      ASPNETCORE_ENVIRONMENT: "Development"
      # MinIO config – internal endpoint only
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_PUBLIC_BUCKET: public
      MINIO_PRIVATE_BUCKET: private
      MINIO_USE_SSL: false
    depends_on:
      minio:
        condition: service_healthy          # Wait for MinIO to be ready
    networks:
      - app-net

  # ==========================
  # Frontend (SwapStreet) – uncomment when needed
  # ==========================
  swapstreet:
    build: ./swapstreet
    container_name: swapstreet-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./swapstreet:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    networks:
      - app-net

  # ==========================
  # MinIO (internal only)
  # ==========================
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "9000"          # Only inside Docker network
    ports:
      - "9001:9001"     # Console (optional)
    networks:
      - app-net

  # ==========================
  # NGINX – public gateway
  # ==========================
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9000:9000"     # Browser → localhost:9000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # ← Mount config
    depends_on:
      - minio
    networks:
      - app-net

# ==========================
# Networks & Volumes
# ==========================
networks:
  app-net:
    driver: bridge

volumes:
  minio_data: