version: "3.9"

services:
  # ==========================
  # Backend service (.NET API)
  # ==========================
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      USE_INMEMORY_DB: "true"
      ASPNETCORE_ENVIRONMENT: "Development"
      # MinIO config
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: swapstreet-files
    depends_on:
      - minio

  # ==========================
  # Frontend (Swapstreet)
  # ==========================
  swapstreet:
    build: ./swapstreet
    container_name: swapstreet-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./swapstreet:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - backend

  # ==========================
  # MinIO (Non-persistent)
  # ==========================
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # No volumes here → non-persistent storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
