version: "3.9"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: swapstreet-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
